const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const header=document.querySelector('.header');
const toggle=document.querySelector('.menu-toggle');
const mobile=document.querySelector('.mobile-nav');
function closeMenu(restore=false){header.classList.remove('menu-active');document.body.classList.remove('menu-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');mobile.inert=true;if(restore)toggle.focus();}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';header.classList.toggle('menu-active',open);document.body.classList.toggle('menu-open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');mobile.inert=!open;if(open)mobile.querySelector('a').focus();});
mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));
document.addEventListener('keydown',e=>{if(toggle.getAttribute('aria-expanded')!=='true')return;if(e.key==='Escape'){closeMenu(true);return;}if(e.key==='Tab'){const controls=[toggle,...mobile.querySelectorAll('a')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.matchMedia('(min-width:901px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
if(!reduced.matches){document.documentElement.classList.add('motion-ready');const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.classList.contains('retention-product'))animateScore();reveal.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));const bridge=document.querySelector('.connection-bridge');const problem=document.querySelector('.problem');if(bridge&&problem){new IntersectionObserver(([entry],observer)=>{if(entry.isIntersecting){problem.classList.add('problem-resolved');observer.disconnect();}},{threshold:.6}).observe(bridge);}}
function animateScore(){const el=document.querySelector('[data-score]');if(!el)return;const start=performance.now();function frame(now){const p=Math.min((now-start)/1100,1);const eased=1-Math.pow(1-p,3);el.textContent=Math.round(68+(4*eased));if(p<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}
const stories=[...document.querySelectorAll('[data-stage]')];
const labels=['Patient identification','Screening workflow','Study enrollment','Protocol-driven randomization','Retention monitoring','Trial completion'];
const problemImpact=document.querySelector('.problem-impact');
const problemCards=[...document.querySelectorAll('.problem-impact-card')];
const problemDepth=[0,.33,.66,1];
let problemProgress=0,problemTarget=0,problemMotionFrame=0,problemMotionTime=0;
function renderProblemMotion(time){const elapsed=problemMotionTime?Math.min((time-problemMotionTime)/1000,.05):1/60;problemMotionTime=time;const blend=1-Math.exp(-elapsed*8);problemProgress+=((problemTarget-problemProgress)*blend);problemCards.forEach((card,i)=>card.style.setProperty('--impact-shift',`${(card.offsetHeight*problemDepth[i]*problemProgress).toFixed(2)}px`));if(Math.abs(problemTarget-problemProgress)>.001)problemMotionFrame=requestAnimationFrame(renderProblemMotion);else{problemProgress=problemTarget;problemMotionFrame=0;problemMotionTime=0;}}
function updateProblemMotion(){if(!problemImpact||!problemCards.length)return;if(reduced.matches||window.innerWidth<=1150){problemTarget=problemProgress=0;problemCards.forEach(card=>card.style.setProperty('--impact-shift','0px'));if(problemMotionFrame)cancelAnimationFrame(problemMotionFrame);problemMotionFrame=0;problemMotionTime=0;return;}const rect=problemImpact.getBoundingClientRect();problemTarget=Math.max(0,Math.min(1,(window.innerHeight-rect.top)/(window.innerHeight+rect.height)));if(!problemMotionFrame)problemMotionFrame=requestAnimationFrame(renderProblemMotion);}
let last=-1,pending=false;
function updateScroll(){header.classList.toggle('scrolled',window.scrollY>25);if(!reduced.matches){const hero=document.querySelector('.hero');if(hero){hero.style.setProperty('--hero-shift',`${Math.min(window.scrollY*.045,28)}px`);}}const focus=window.innerHeight*.5;let active=0;stories.forEach((s,i)=>{if(s.getBoundingClientRect().top<focus)active=i;});if(active!==last){last=active;document.querySelectorAll('[data-step]').forEach((el,i)=>{if(i===active)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});document.querySelectorAll('[data-signal]').forEach((el,i)=>el.classList.toggle('active',i===active));const status=document.querySelector('#lifecycle-status');const canvas=document.querySelector('.lifecycle-canvas');if(status)status.textContent=labels[active];if(canvas)canvas.dataset.active=active;}updateProblemMotion();pending=false;}
window.addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(updateScroll);}},{passive:true});window.addEventListener('load',updateScroll);window.addEventListener('resize',updateScroll);updateScroll();
reduced.addEventListener('change',e=>{document.documentElement.classList.toggle('motion-ready',!e.matches);updateScroll();});
const dialog=document.querySelector('#legal-dialog');document.querySelectorAll('[data-legal]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#legal-title').textContent=b.dataset.legal;document.querySelector('#legal-topic').textContent=b.dataset.legal==='Privacy'?'privacy policy':'terms of use';dialog.showModal();}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
