import { mkdir, writeFile, cp } from 'node:fs/promises';
import { Navbar, Footer } from './src/components/navigation.mjs';
import { Hero } from './src/components/hero.mjs';
import { TrialLifecycle } from './src/components/lifecycle.mjs';
import { ProblemSection, RetentionIndex, TrialTeamSection, ResearchEnterprise, BrandMoment, CTA } from './src/components/sections.mjs';
await mkdir('dist', { recursive:true });
await cp('public','dist',{recursive:true});
await cp('src/styles.css','dist/styles.css');
await cp('src/main.js','dist/main.js');
await writeFile('dist/index.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ClinTrialAI | AI-Powered Clinical Trial Execution</title><meta name="description" content="ClinTrialAI provides one intelligent AI productivity layer across the clinical trial lifecycle—from patient identification and screening to enrollment, retention and trial completion."><meta name="theme-color" content="#f7f8f6"><meta property="og:title" content="ClinTrialAI | AI-Powered Clinical Trial Execution"><meta property="og:description" content="One intelligent AI productivity layer across the clinical trial lifecycle."><meta property="og:type" content="website"><link rel="icon" href="images/favicon-clintrialai.png"><link rel="stylesheet" href="styles.css"><script type="module" src="main.js"></script></head><body><a class="skip" href="#main">Skip to content</a>${Navbar()}<main id="main">${Hero()}${TrialLifecycle()}${ProblemSection()}${RetentionIndex()}${TrialTeamSection()}${ResearchEnterprise()}${BrandMoment()}${CTA()}</main>${Footer()}</body></html>`);
console.log('Built homepage → dist/index.html');
