const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const header=document.querySelector('.header');
const toggle=document.querySelector('.menu-toggle');
const mobile=document.querySelector('.mobile-nav');
function closeMenu(restore=false){header.classList.remove('menu-active');document.body.classList.remove('menu-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');mobile.inert=true;if(restore)toggle.focus();}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';header.classList.toggle('menu-active',open);document.body.classList.toggle('menu-open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');mobile.inert=!open;if(open)mobile.querySelector('a').focus();});
mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));
document.addEventListener('keydown',e=>{if(toggle.getAttribute('aria-expanded')!=='true')return;if(e.key==='Escape'){closeMenu(true);return;}if(e.key==='Tab'){const controls=[toggle,...mobile.querySelectorAll('a')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.matchMedia('(min-width:901px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
if(!reduced.matches){document.documentElement.classList.add('motion-ready');const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.classList.contains('retention-product'))animateScore();reveal.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));}
function animateScore(){const el=document.querySelector('[data-score]');const start=performance.now();function frame(now){const p=Math.min((now-start)/1200,1);el.textContent=Math.round(72*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}
const stories=[...document.querySelectorAll('[data-stage]')];
const labels=['Patient identification','Screening workflow','Study enrollment','Protocol-driven randomization','Retention monitoring','Trial completion'];
let last=-1,pending=false;
function updateScroll(){header.classList.toggle('scrolled',window.scrollY>25);const focus=window.innerHeight*.5;let active=0;stories.forEach((s,i)=>{if(s.getBoundingClientRect().top<focus)active=i;});if(active!==last){last=active;document.querySelectorAll('[data-step]').forEach((el,i)=>{if(i===active)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});document.querySelectorAll('[data-signal]').forEach((el,i)=>el.classList.toggle('active',i===active));document.querySelector('#lifecycle-status').textContent=labels[active];document.querySelector('.lifecycle-canvas').dataset.active=active;}pending=false;}
window.addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(updateScroll);}},{passive:true});window.addEventListener('load',updateScroll);window.addEventListener('resize',updateScroll);updateScroll();
reduced.addEventListener('change',e=>{document.documentElement.classList.toggle('motion-ready',!e.matches);});
const dialog=document.querySelector('#legal-dialog');document.querySelectorAll('[data-legal]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#legal-title').textContent=b.dataset.legal;document.querySelector('#legal-topic').textContent=b.dataset.legal==='Privacy'?'privacy policy':'terms of use';dialog.showModal();}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
